### ISSUE TITLE
Metaphlan Conda Repository

### ISSUE THREAD

**Issue by MichWeb75** [biobakery/MetaPhlAn#105]
The Metaphlan conda repository depends on 
`samtools >=0.1.19,<1.0 . `

I am wondering if this can be changed to the most recent samtools version ? Why is it limited to 1.0 ?

**Comment by fbeghini** [comment]
Hi @MichWeb75,
the requirements you mentioned here is related to MetaPhlAn2, which had to use a specific version of `samtools` since StrainPhlAn was requiring a specific output format that was kept only to such versions.
If you are not interested in using StrainPhlAn, you can upgrade samtools to a more recent version. The usage of samtools is limited to StrainPhlAn, since MetaPhlAn2 does not uses it internally.
In the latest MetaPhlAn 3.0 recipe, you can use the latest version of `samtools`
