### ISSUE TITLE
Comparing the results of Metaphlan and Kraken2

### ISSUE THREAD

**Issue by Maryamtarazkar** [biobakery/MetaPhlAn#114]
I ran one sample through Metaphlan2 and kraken2 for classification. But the results from Metaphlan2 and Kraken2 is completely different. I am not sure which one I have to rely? Any insight would be greatly appreciated

**Comment by kescobo** [comment]
See my response  to #90 - the two tools use very different approaches. 

For discussing how to reason about the trade-offs between them, please ask [on the forums](https://forum.biobakery.org/c/Microbial-community-profiling/MetaPhlAn/7) - I think it's a really valuable discussion to have available for people to refer to, but issues here on GitHub are really intended for bugs or issues with the software implementation itself, rather than general discussions about usage.

**Comment by Maryamtarazkar** [comment]
> See my response  to #90 - the two tools use very different approaches.
> For discussing how to reason about the trade-offs between them, please ask on the forums - I think it's a really valuable discussion to have available for people to refer to, but issues here on GitHub are really intended for bugs or issues with the software implementation itself, rather than general discussions about usage.

**Comment by Maryamtarazkar** [comment]
Thank yo very much for your note. You are absolutely right.
