### ISSUE TITLE
Can SARS-CoV2 be added to metaphlan database? 

### ISSUE THREAD

**Issue by elzerac** [biobakery/MetaPhlAn#116]
Hello, 

I am working on metatranscriptomic sequencing of nasal samples with known SARS-CoV2 positivity and I am getting hits in the "Bell pepper endornavirus" as the sole viral hit, where I would expect to get a SARS-CoV2 hit. Could you let me know why this is happening and could the metaphlan databse be updated with the most recent SARS-CoV2 genomes so that we and others could utilize your tool for COVID-19 studies? 

Thank you! 

Best, 

Elze

**Comment by kescobo** [comment]
I can tell you why - the current metaphlan database was created in early 2019 IIRC, before CoV2 was a thing.
I can't speak to the likelihood of a database update.

**Comment by fbeghini** [comment]
Like @kescobo said, the latest database was built in early 2019, plus the virus markers were not generated using the new pipeline since is not suitable for finding markers in viruses and so they are the same markers that are present in MetaPhlAn2.
We are not planning on update the database in the following months, but even so, an update will affect only the bacterial/archaeal/eukariote species. We'll work on a supplementary pipeline for identify viral markers.

**Comment by elzerac** [comment]
Would be very nice to have a pipeline for viral markers, including SARS-CoV2. Thank you.
