### ISSUE TITLE
installation of release v3.0 fails

### ISSUE THREAD

**Issue by genio0815** [biobakery/MetaPhlAn#77]
Hi,

the 3.0 release lacks the 'metaphlan.py' file in main directory and in the one found in /metaphlan 
the function 'check_and_install_database' in undefined:
`metaphlan/metaphlan.py", line 915, in main
    pars['index'] = check_and_install_database(pars['index'], pars['bowtie2db'], pars['bowtie2_build'], pars['nproc'], pars['force_download'])
NameError: name 'check_and_install_database' is not defined`

best,

**Comment by fbeghini** [comment]
Hi,
have you installed the software with pip install . or just executed the py
script?

----
*Francesco Beghini*
*PhD Student*

Lab. of Computational Metagenomics
Department of Cellular, Computational and Integrative Biology - CIBIO
University of Trento
Via Sommarive 9, 38123 Trento, Italy

**Comment by genio0815** [comment]
HI,

i tested the source code tarball tagged as v3.0
https://github.com/biobakery/MetaPhlAn/archive/3.0.tar.gz

cheers,

**Comment by fbeghini** [comment]
From the root folder, the one that contains the setup.py file, you should
run "pip install ." in order to install MetaPhlAn and make it runnable
----
*Francesco Beghini*
*PhD Student*

Lab. of Computational Metagenomics
Department of Cellular, Computational and Integrative Biology - CIBIO
University of Trento
Via Sommarive 9, 38123 Trento, Italy

**Comment by genio0815** [comment]
Sry, obviously I did not look closely enough at how this is packed (was previously slightly different).
Thanks
