### ISSUE TITLE
please provide tagged version for metaphlan2-2.96.1

### ISSUE THREAD

**Issue by EricDeveaud** [biobakery/MetaPhlAn#94]
I have to rebuild metaphlan2-2.96.1 that I previously grabbed from bitbucket,
https://bitbucket.org/biobakery/metaphlan2/get/2.96.1.tar.gz

this specific version is not available on github releases, nor tagged.

please provide a way to re-install this specific version
regards

Eric

**Comment by fbeghini** [comment]
Hi Eric,
MetaPhlAn2 2.96.1 is what is now MetaPhlAn 3, we opted for a change of version since the edits were quite a lot for a minor version. The same algorithm and options present in v2.96.1 are present in v3, with some updates in the database retrieval from a different source.
If you are still interested in using 2.96.1 version, this commit 9365461a17cb6355ae4d7102b2d7abdc73de81f9 was used to tag the software

**Comment by EricDeveaud** [comment]
thanks. 
I will be abble to re-install version 2.96.1 as per request (need to re-run some computations using the exact same version) and I will alos provide latest version 3

regards

Eric
